name: plant_tribes_kaks_analysis_distribution
owner: greg
description: |
  Contains a tool that draws a histogram of the significant components in the ks distribution.
homepage_url: https://github.com/dePamphilis/PlantTribes
long_description: |
  Contains a tool that draws a histogram of the significant components in the ks distribution.
remote_repository_url: https://github.com/gregvonkuster/galaxy_tools/tree/master/tools/plant_tribes/kaks_analysis_distribution
type: unrestricted
categories:
- Phylogenetics
