sudo: false
language: python
python: 2.7

env:
  global:
    - PLANEMO_TEST_SCRIPT=https://raw.githubusercontent.com/galaxyproject/planemo/master/scripts/run_galaxy_workflow_tests.sh
    - PLANEMO_TEST_STYLE=serve_and_test
    - PLANEMO_TARGET="planemo==0.52.0"
    - PLANEMO_GALAXY_BRANCH="release_18.05"
   matrix:
    - WORKFLOW_TEST=workflow_tests/extract_ipm_date_interval/extract_ipm_date_interval_1.ga

before_install:
  - export GALAXY_REPO=https://github.com/galaxyproject/galaxy
  - export GALAXY_RELEASE=release_17.09
  - export PLANEMO_CONDA_PREFIX="$HOME/conda"
  - unset JAVA_HOME

install:
  - pip install planemo
  - planemo conda_init
  - export PATH="$PLANEMO_CONDA_PREFIX/bin:$PATH"
  - conda create -y -q -c bioconda --name iuc_conda bcftools
  - . activate iuc_conda
  - planemo --version
  - conda --version
  - git diff --quiet "$TRAVIS_COMMIT_RANGE" -- ; GIT_DIFF_EXIT_CODE=$?
  - |
    if [ "$GIT_DIFF_EXIT_CODE" -gt 1 ] ; then
        git remote set-branches --add origin master
        git fetch
        TRAVIS_COMMIT_RANGE=origin/master...
    fi
  - echo $TRAVIS_COMMIT_RANGE
  - |
    planemo ci_find_repos --exclude data_managers \
                          --exclude packages \
                          --exclude_from .tt_blacklist \
                          --changed_in_commit_range "$TRAVIS_COMMIT_RANGE" \
                          --output changed_repositories.list
  - touch changed_repositories.list changed_tools.list
  - |
    if [ -s changed_repositories.list ]; then
        if [ $(wc -l < changed_repositories.list) -eq 1 ]; then
            planemo ci_find_tools --output changed_tools.list $(cat changed_repositories.list)
        else
            planemo ci_find_repos --output changed_repositories.list $(cat changed_repositories.list)
        fi
    fi
  - cat changed_repositories.list

script:
  - set -e
  - while read -r DIR; do planemo shed_lint --tools --ensure_metadata --urls --report_level warn --fail_level error --recursive "$DIR"; done < changed_repositories.list
  - while read -r DIR; do planemo conda_install "$DIR"; done < changed_repositories.list
  - while read -r DIR; do planemo test --conda_dependency_resolution --galaxy_branch "$GALAXY_RELEASE" --galaxy_source "$GALAXY_REPO" "$DIR"; done < changed_repositories.list
  - bash <(curl -s "$PLANEMO_TEST_SCRIPT") "$WORKFLOW_TEST"

services:
  - postgres
